Made changes to collate_fn . CUDA assertion error
Collate_fn: Processes only one cropped image at a time 
Error: AcceleratorError: CUDA error: device-side assert triggered
Search for `cudaErrorAssert